---
# Navigation
active: about
# Sitemap
canonical: https://ismaywolff.nl/about
---
{% extends "lib/base/base.swig" %}

{% block title %}About · {{ siteTitle }}{% endblock %}

{% block content %}
  <section>
    <div class="Segment u-textCenter">
      <h2 class="Title Title--main">About</h2>
    </div>
    <div class="Segment Segment--text">
      <p>About pagina</p>
    </div>
  </section>
{% endblock %}
